In [31]:
import os
from selenium import webdriver
import pandas as pd
import time
from selenium.webdriver.support.ui import Select

In [4]:
DONWLOAD_FOLDER = os.path.join(os.getcwd(), "downloads")

In [116]:
chromeOptions = webdriver.ChromeOptions()
prefs = {"download.default_directory": DONWLOAD_FOLDER}
chromeOptions.add_experimental_option("prefs", prefs)
DRIVER = webdriver.Chrome(options=chromeOptions)

In [117]:
KEYWORD = "serum"

In [118]:
DRIVER.get(f'https://hpo.jax.org/app/browse/search?q={KEYWORD}&navFilter=all')

In [119]:
def get_all_rows():
    "Changes the row values from 50, to 500"
    DRIVER.find_element_by_id("mat-select-0").click()
    time.sleep(1)
    DRIVER.find_element_by_id("mat-option-2").click()

In [120]:
get_all_rows()

In [121]:
headers = ["Term Identifier", "Term Name", "Matching String", "No. Descendants"]

In [122]:
def get_pandas_rows(header):
    "Collect the table, and parse it into a pandas data frame"
    rows = DRIVER.find_elements_by_class_name('mat-row.cdk-row.ng-star-inserted')
    serum = pd.DataFrame([row.text.split("\n") for row in rows], columns=headers)
    return serum

In [123]:
serum_df = get_pandas_rows(headers)

In [124]:
serum_df

,Term Identifier,Term Name,Matching String,No. Descendants
0,HP:0010876,Abnormal circulating protein concentration,Serum protein abnormality,141
1,HP:0010701,Abnormal immunoglobulin level,Abnormal serum immunoglobulin levels,132
2,HP:0003112,Abnormal circulating amino acid concentration,Abnormality of serum amino acid level,103
3,HP:0004313,Decreased circulating antibody level,Decreased serum immunoglobulin,65
4,HP:0010702,Increased circulating antibody level,Increased serum gamma globulin,38
...,...,...,...,...
148,HP:0010837,Decreased circulating ceruloplasmin concentration,Decreased serum ceruloplasmin,0
149,HP:0012053,Decreased circulating calcifediol concentration,Low serum calcidiol,0
150,HP:0004319,Decreased circulating aldosterone level,Decreased serum aldosterone,0
151,HP:0020171,Decreased blood drug concentration,Reduced serum drug concentrations,0
152,HP:0030167,Antimitochondrial antibody positivity,Serum antimitochrondrial antibodies,0

## Crawler + Parser

In [77]:
def crawler(url, chromeOptions):
    driver = webdriver.Chrome(options=chromeOptions)
    driver.get(url)
    time.sleep(2)
    driver.find_element_by_class_name("mat-focus-indicator.download-associations.mat-raised-button.mat-button-base").click()
    time.sleep(2)
    try:
        driver.find_elements_by_class_name("mat-focus-indicator.dialog-selection.mat-raised-button.mat-button-base")[0].click()
        time.sleep(3)
    except IndexError:
        print('Esta url no tiene dataset')
    driver.quit()

In [78]:
for x in serum_df["Term Identifier"]:
    url = "https://hpo.jax.org/app/browse/term/" + x
    crawler(url, chromeOptions)

Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset
Esta url no tiene dataset

In [100]:
dfs = []
for xlsx in os.listdir('downloads'):
    lab_term = xlsx[13:23].replace("_", ":")
    df = pd.read_excel("downloads/" + xlsx)
    df['Term Identifier'] = lab_term
    dfs.append(df)

C:\Users\54226\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [101]:
complete_disease_edges = pd.concat(dfs)

In [105]:
complete_disease_edges

,DISEASE_ID,DISEASE_NAME,Term Identifier
0,ORPHA:1772,"45,x/46,xy Mixed Gonadal Dysgenesis",HP:0000837
1,OMIM:273250,"46, Xy Sex Reversal 11",HP:0000837
2,ORPHA:243,"46,xx Gonadal Dysgenesis",HP:0000837
3,ORPHA:90796,"46,xy Disorder Of Sex Development Due To Isola...",HP:0000837
4,ORPHA:168558,"46,xy Disorder Of Sex Development-adrenal Insu...",HP:0000837
...,...,...,...
2,ORPHA:90793,Congenital Adrenal Hyperplasia Due To 17-alpha...,HP:0500022
3,ORPHA:90791,Congenital Adrenal Hyperplasia Due To 3-beta-h...,HP:0500022
4,ORPHA:361,Familial Glucocorticoid Deficiency,HP:0500022
0,OMIM:245400,Mitochondrial Dna Depletion Syndrome 9 (enceph...,HP:0500181
1,ORPHA:3008,Pyruvate Carboxylase Deficiency,HP:0500181

In [107]:
grouped = complete_disease_edges[["DISEASE_ID", "Term Identifier"]].groupby(by=["Term Identifier"]).count()

In [112]:
grouped

                 DISEASE_ID
Term Identifier
HP:0000837               72
HP:0000848               24
HP:0002151              187
HP:0002153               46
HP:0002155              113
...                     ...
HP:0410050                1
HP:0410054                1
HP:0410246                2
HP:0500022                5
HP:0500181                2

[128 rows x 1 columns]

In [136]:
serum_complete = serum_df

In [137]:
serum_complete = serum_complete.merge(grouped, how='left', on="Term Identifier")

In [138]:
serum_complete

,Term Identifier,Term Name,Matching String,No. Descendants,DISEASE_ID
0,HP:0010876,Abnormal circulating protein concentration,Serum protein abnormality,141,685.0
1,HP:0010701,Abnormal immunoglobulin level,Abnormal serum immunoglobulin levels,132,354.0
2,HP:0003112,Abnormal circulating amino acid concentration,Abnormality of serum amino acid level,103,152.0
3,HP:0004313,Decreased circulating antibody level,Decreased serum immunoglobulin,65,229.0
4,HP:0010702,Increased circulating antibody level,Increased serum gamma globulin,38,148.0
...,...,...,...,...,...
148,HP:0010837,Decreased circulating ceruloplasmin concentration,Decreased serum ceruloplasmin,0,6.0
149,HP:0012053,Decreased circulating calcifediol concentration,Low serum calcidiol,0,1.0
150,HP:0004319,Decreased circulating aldosterone level,Decreased serum aldosterone,0,23.0
151,HP:0020171,Decreased blood drug concentration,Reduced serum drug concentrations,0,NaN
152,HP:0030167,Antimitochondrial antibody positivity,Serum antimitochrondrial antibodies,0,3.0

In [139]:
serum_complete['DISEASE_ID'].isna().sum()

25

In [141]:
from IPython.display import FileLink, FileLinks

In [142]:
path = os.getcwd()

In [145]:
compression_opts = dict(method='zip',
                        archive_name='serum.csv')  
serum.to_csv('out.zip', index=False,
          compression=compression_opts)